[EVM]
[[EVM.Nodes]]
Name = "ganache"
WSURL = "ws://192.168.34.106:8545"
HTTPURL = "http://192.168.34.106:8545"
ChainID = "5777"

[Log]
Level = "debug"

[WebServer]
HTTPPort = 6688
TLS = { Port = 0 }
SecureCookies = false
