type = "cron"
schemaVersion = 1
name = "WETH/USD Price"
forwardingAllowed = false
maxTaskDuration = "0s"
schedule = "@every 3m"
observationSource = """
fetch    [type="http" method="GET" url="https://api.binance.com/api/v3/ticker/price?symbol=ETHUSDT" allowUnrestrictedNetworkAccess=true]\n
parse    [type="jsonparse" path="price" data="$(fetch)"]\n
multiply [type="multiply" input="$(parse)" times=100000000]\n
encode   [type="ethabiencode" abi="updatePrice(string symbol, int256 price)" data="{\\\"symbol\\\": \\\"WETH\\\", \\\"price\\\": $(multiply)}"]\n
submit   [type="ethtx" to="0x9eE64780609935da5240349341bf87656280263C" data="$(encode)" gasLimit="500000"]\n
fetch->parse->multiply->encode->submit
"""