type = "cron"
schemaVersion = 1
name = "LINK/USD Price"
forwardingAllowed = false
maxTaskDuration = "0s"
schedule = "@every 30s"
observationSource = """
fetch    [type="http" method="GET" url="https://api.binance.com/api/v3/ticker/price?symbol=LINKUSDT" allowUnrestrictedNetworkAccess=true]\n
parse    [type="jsonparse" path="price" data="$(fetch)"]\n
multiply [type="multiply" input="$(parse)" times=100000000]\n
encode   [type="ethabiencode" abi="updatePrice(string symbol, int256 price)" data="{\\\"symbol\\\": \\\"LINK\\\", \\\"price\\\": $(multiply)}"]\n
submit   [type="ethtx" to="0x8F1ca3805570b06cF7fD29eDb7d0B11412b65eFA" data="$(encode)" gasLimit="500000"]\n
fetch->parse->multiply->encode->submit
"""

