type = "cron"
schemaVersion = 1
name = "USDC/USD Price"
forwardingAllowed = false
maxTaskDuration = "0s"
schedule = "@every 3m"
observationSource = """
fetch    [type="http" method="GET" url="https://api.binance.com/api/v3/ticker/price?symbol=USDCUSDT" allowUnrestrictedNetworkAccess=true]\n
parse    [type="jsonparse" path="price" data="$(fetch)"]\n
multiply [type="multiply" input="$(parse)" times=100000000]\n
encode   [type="ethabiencode" abi="updatePrice(string symbol, int256 price)" data="{\\\"symbol\\\": \\\"USDC\\\", \\\"price\\\": $(multiply)}"]\n
submit   [type="ethtx" to="0x6dA1D4597968AEcD71103Faa5f15Ac28056c47B1" data="$(encode)" gasLimit="500000"]\n
fetch->parse->multiply->encode->submit
"""