type = "cron"
schemaVersion = 1
name = "ETH/USD Every 30s"
schedule = "@every 30s"

observationSource = """
fetch    [type="http" method="GET" url="https://api.binance.com/api/v3/ticker/price?symbol=ETHUSDT" allowUnrestrictedNetworkAccess=true]
parse    [type="jsonparse" path="price" data="$(fetch)"]
multiply [type="multiply" input="$(parse)" times=100000000]
encode   [type="ethabiencode" abi="updateAnswer(int256)" data="{\"answer\": $(multiply)}"]
submit   [type="ethtx" to="0xaade571B01122187B3703A84190D5245f70ae94b" data="$(encode)"]
fetch -> parse -> multiply -> encode -> submit
"""
