type = "cron"
schemaVersion = 1
name = "ETH/USD Every 2"
forwardingAllowed = false
maxTaskDuration = "0s"
schedule = "@every 30s"
observationSource = """
fetch    [type="http" method="GET" url="https://api.binance.com/api/v3/ticker/price?symbol=ETHUSDT" allowUnrestrictedNetworkAccess=true]\n
parse    [type="jsonparse" path="price" data="$(fetch)"]\n
multiply [type="multiply" input="$(parse)" times=100000000]\n
encode   [type="ethabiencode" abi="updateAnswer(int256 answer)" data="{\\\"answer\\\": $(multiply)}"]\n
submit   [type="ethtx" to="0xEdFd8Ea42fc72f5a358d3B88Ed516D92bD9aEE1B" data="$(encode)"]\n
fetch->parse->multiply->encode->submit
"""







































