type = "cron"
schemaVersion = 1
name = "DAI/USD price"
forwardingAllowed = false
maxTaskDuration = "0s"
schedule = "@every 3m"
observationSource = """
fetch    [type="http" method="GET" url="https://api.binance.com/api/v3/ticker/price?symbol=USDTDAI" allowUnrestrictedNetworkAccess=true]\n
parse    [type="jsonparse" path="price" data="$(fetch)"]\n
# p_scaled = price * 1e8 (USDT/DAI)
scale    [type="multiply" input="$(parse)" times=100000000]\n
# invert_scaled = 1e16 / p_scaled  => DAI/USD with 8 decimals
invert   [type="divide" input="10000000000000000" divisor="$(scale)"]\n
# invert đã là số nguyên 8 decimals nếu đầu vào có 8 decimals
encode   [type="ethabiencode" abi="updatePrice(string symbol, int256 price)" data="{\\\"symbol\\\": \\\"DAI\\\", \\\"price\\\": $(invert)}"]\n
submit   [type="ethtx" to="0xF7Cf68Af058D59cDF5f606bC1bBA3a024b0eB5b4" data="$(encode)" gasLimit="500000"]\n
fetch->parse->scale->invert->encode->submit
"""