[Log]
Level = 'debug'

[WebServer]
AllowOrigins = '*'
SecureCookies = false
TLS.HTTPSPort = 0

[WebServer.RateLimit]
Authenticated = 1000
Unauthenticated = 100


[[EVM]]
ChainID = '1337'

[[EVM.Nodes]]
Name = 'Ganache'
WSURL = 'ws://host.docker.internal:7545'
HTTPURL = 'http://host.docker.internal:7545'

[EVM.GasEstimator]
Mode = 'FixedPrice'

[EVM.GasEstimator.FixedPrice]
PriceDefault = '20 gwei'
PriceMax = '50 gwei'

[EVM.HeadTracker]
HistoryDepth = 10

[EVM.Transactions]
MaxInFlight = 16
MaxQueued = 250
ReaperInterval = '1h'
ReaperThreshold = '168h'
ResendAfterThreshold = '1m'

[Feature]
LogPoller = true

# Secrets file location
# Chainlink 2.2.0 will look for secrets.toml in the data directory (/chainlink/secrets.toml)







