[WebServer]
AllowOrigins = "*"
SecureCookies = false
HTTPPort = 6688

[WebServer.TLS]
HTTPSPort = 0

[Log]
Level = "info"

[[EVM]]
ChainID = 31337
Enabled = true

[[EVM.Nodes]]
Name = "hardhat"
WSURL = "ws://host.docker.internal:8545"
HTTPURL = "http://host.docker.internal:8545"

[Feature]
LogPoller = true






